version: 2

sources:
  - name: raw
    schema: raw_gz
    description: sales of gz
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: <gzsales>
      - name: product
        identifier: raw_gz_product
        description: <gzproduct>
      - name: ship
        identifier: raw_gz_ship
        description: <gzship>
