version: 2

sources:
  - name: raw
    schema: raw_gz
    description: sales of gz
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Sales of Greenweez
        tests:
              - unique:
                  column_name: "orders_id || '-' || pdt_id"
        columns:
          - name: date_date
            description: date of the purchase
          - name: orders_id
            description: each order done by each customer
          - name: quantity
            description: quantity ordered by each customer
          - name: revenue
            description: turnover for each product
          - name: pdt_id
            description: each product ordered by each customer

      - name: product
        identifier: raw_gz_product
        description: Products of Greenweez
        columns:
          - name: date_date
            description: date of the purchase
          - name: products_id
            description: Primary Key - ID of each product
            tests:
              - unique
              - not_null

      - name: ship
        identifier: raw_gz_ship
        description: Shipping from Greenweez
        columns:
          - name: orders_id
            description: Primary Key - ID of each order
            tests:
              - unique
              - not_null

          - name: shipping_fee
            description: shipping fee per order
          - name: log_cost
            description: logistic costs
          - name: ship_cost
            description: ship cost paid by customer 

            
      - name: facebook
        identifier: raw_gz_facebook
        description: results from facebook
        tests:
              - unique:
                  column_name: "date_date || '-' || campaign_key"

            
      - name: criteo
        identifier: raw_gz_criteo
        description: results from criteo
        tests:
              - unique:
                  column_name: "date_date || '-' || campaign_key"

            
      - name: adwords
        identifier: raw_gz_adwords
        description: results from adwords 
        tests:
              - unique:
                  column_name: "date_date || '-' || campaign_key"    

      - name: bing
        identifier: raw_gz_bing
        description: results from bing
        tests:
              - unique:
                  column_name: "date_date || '-' || campaign_key"

models:
  - name: stg_raw__sales
  - name: stg_raw__ship
  - name: stg_raw__product
  - name: int_sales_margin 
  - name: int_orders_margin 
  - name: int_orders_operational
  - name: finance_days
  - name: stg_raw_criteo
  - name: stg_raw_facebook
  - name: stg_raw_bing
  - name: stg_raw_adwords
  - name: int_campaigns
  - name: int_campaigns_day
  - name: finance_campaigns_day
  - name: finance_campaigns_month